from .YOLO11 import YOLO11_CLS,YOLO_RESULT_CLS
from .YOLO11 import YOLO11_DET,YOLO_RESULT_DET
from .FACE_DETECT import FACE_DETECT,FACE_DETECT_RESULT
from .PERSON_DETECT import PERSON_DETECT,PERSON_DETECT_RESULT
